<div class="content-region">

      <h6>PRIVACY AND ONLINE DATA COLLECTION NOTICE</h6>
      <h4>Effective October 30th, 2014</h4>
      
      <p>IMPORTANT!  These Terms and Conditions (“Terms and Conditions”) govern your (the “User” or “You” or “Your”) use of the http://www.lightningecon.org Web Site (the “Web Site”) provided by Lightning Abstracts.  By accessing or using the Web Site, You are a “User” and You accept and agree to the Terms and Conditions below as a legal and binding contract between You and Lightning Abstracts.  These Terms and Conditions are subject to change by Lightning Abstracts at any time in its discretion and any such changes to the Terms and Conditions will be applicable to all subsequent access to or use of the Web Site.  Your use of the Web Site after such changes are implemented constitutes your acceptance of the changes.  Please consult these Terms and Conditions regularly. <br><br>If You do not accept and agree to all provisions of the Terms and Conditions of this Web Site, now or in the future, You reject the Terms and Conditions and shall immediately terminate Your access and use of the Web Site.  Any continued use or access by You of the Web Site, without Your acceptance and agreement with all provisions of the Terms and Conditions, is unauthorized.<br><br>By accepting the Terms and Conditions of this Web Site, You are also required to comply with and to ensure compliance with all laws, ordinances, and regulations applicable to your activities on the Web Site.<br><br>This Web Site is intended and designed for Users 18 years of age and older, and access or use by anyone younger is not authorized.</p>
      
      <h6>TABLE OF CONTENTS</h6>
      <ul>
        <li>Our Commitment to Privacy</li>
        <li>The Information We Collect</li>
        <li>How We Use Information</li>
        <li>Our Commitment to Data Security</li>
        <li>Our Commitment to Children’s Privacy</li>
        <li>How to Access or Correct Your Information</li>
        <li>Changes Regarding this Privacy and Online Data Collection Notice</li>
        <li>How to Contact Us</li>
      </ul>
      
      <h6>OUR COMMITMENT TO PRIVACY</h6>
      
      <p>Your privacy is important to us.  To better protect your privacy, we provide this notice explaining our online information practices and the choices you can make about the way your information is collected and used.  At Lightning Abstracts, we will never sell, rent, trade or license, in whole-part or piecemeal, any information that we hold about or relating to you, however gathered, to any third-party. Access to your information with Lightning Abstracts will be restricted and accessible only where necessary to the function for which it was collected.  To make this notice easy to find, we make it available on our homepage and at every point where personally identifiable information may be requested.</p>


      <h6>THE INFORMATION WE COLLECT</h6>

      <p>This notice applies to all information collected or submitted on the Lightning Abstracts web site.  The types of personal information collected by Lightning Abstracts’ web pages are:</p>

      <ul>
        <li>Name</li>
        <li>Email address</li>
      </ul>

      <p>You may elect to provide the following information for specific activities on our website:</p>

      <ul>
        <li>Address(es)</li>
        <li>Phone number</li>
        <li>Credit/Debit card information</li>
      </ul>

      <h6>HOW WE USE INFORMATION</h6>
      
      <p>We use the information you provide about yourself in order to send our monthly bulletins and to complete transactions.  We do not share this information with outside parties. We will also occasionally email you to remind you of or introduce new products.  Such addresses are not used for any other purpose and are not shared with outside parties.<br><br>You can “like us on Facebook” if you would like to receive special offers or announcements of service updates.  Information you submit on our website will otherwise not be used for this purpose.<br><br>We use non-identifying and aggregate information to better design our web site and to share with potential advertisers.  For example, we may tell an advertiser that x number of individuals visited a certain area on our website, or that y number of people filled out our registration form, but we would not disclose anything that could be used to identify those individuals.<br><br>Passed data is information about yourself that you actively and willfully pass to us by explicitly engaging in active functions on the Lightning Abstracts web site, such as contacting us through the Lightning Abstracts web site email contact form.  Lightning Abstracts reserves the right, in its sole discretion, to immediately remove any information generated by you relating to yourself, another person, web site, entity or other organization that Lightning Abstracts determines might be disagreeable to Lightning Abstracts or others.<br><br>Finally, we never use or share the personally identifiable information provided to us online in ways unrelated to the ones described above, including generating cross-reference or collate-passed and passive data to generate “user profiles,” without also providing you an opportunity to opt-out or otherwise prohibit such unrelated uses.  We never seek any more information except that which is absolutely necessary for the desired action to be completed.  We do not place “cookies” (small text files) on your system for any reason.</p>

      <h6>OUR COMMITMENT TO DATA SECURITY</h6>

      <p>To prevent unauthorized access, maintain data accuracy, and ensure the correct use of information, we have put in place appropriate physical, electronic, and managerial procedures to safeguard and secure the information we collect online to protect the integrity of your data, at least as carefully as it would for Lightning Abstracts’ data, against modification, disclosure or destruction.  In the event it is discovered that unauthorized access to data occurred, accidentally or otherwise, Lightning Abstracts will attempt to immediately notify you and explain Lightning Abstracts’ remedial action.</p>

      <h6>OUR COMMITMENT TO CHILDREN’S PRIVACY</h6>

      <p>Protecting the privacy of the very young is very important.  For that reason, Lightning Abstracts never collects or maintains information at our website from those we actually know are under 13, and no part of our web site is structured to attract anyone under 13.</p>

      <h6>HOW TO ACCESS OR CORRECT YOUR INFORMATION</h6>

      <p>You can access all your personally identifiable information that we collect online and maintain by reviewing your profile via the links on every page of our website.  We use this procedure to better safeguard your information.<br><br>You can correct factual errors in your personally identifiable information by changing your profile online, or by sending us a request that credibly shows error.  You can, at any time, request that Lightning Abstracts permanently erase any and all of your personal and identifiable information directly related to yourself at any time and Lightning Abstracts will take action regarding your request as quickly as reasonably possible and notify you when the action is completed.<br><br>To protect your privacy and security, we will also take reasonable steps to verify your identify before granting access or making corrections.</p>

      <h6>CHANGES REGARDING THIS PRIVACY AND ONLINE DATA COLLECTION NOTICE</h6>

      <p>Lightning Abstracts reserves the right to change or modify the terms of this Privacy and Online Data Collection Notice and shall take reasonable action to notify Lightning Abstracts users of any changes.</p>

      <h6>HOW TO CONTACT US</h6>

      <p>Should you have other questions or concerns about these privacy policies, please email us at abstracts@ColoradoCollege.edu.</p>

  </div>

